### ISSUE TITLE
[whc-catalog] upgrade gitlab to sameersbn/gitlab:10.5.6?

### ISSUE THREAD

**Issue by denghongcai** [WebHostingCoopTeam/whc-catalog#1]
thanks for your work, how about upgrade your catalog to latest gitlab ce?

and convoy-nfs is deprecated, how about upgrade to rancher-nfs?

**Comment by joshuacox** [comment]
Because I am not using this catalog anymore.  Though I'll gladly approve PRs.
Rancher is moving to kubernetes, so am I.  So my focus is this page:
https://docs.gitlab.com/ee/install/kubernetes/
although right now I do still use this:
https://github.com/joshuacox/docker-gitlab but am migrating to the above.
